### ISSUE TITLE
Docker should not be a requirement for the initial build and test

### ISSUE THREAD

**Issue by starksm64** [wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-crud#1]
In my experience, docker is too steep of a requirement for an out of the box quick start. I have had problems running it on 4 different developer environments due to version problems and bugs. We should be able to run and test locally with nothing more than java, maven, git.

**Comment by heiko-braun** [comment]
Without docker, running any production ready DB locally adds a lot of overhead too.
Hence I would suggest, without docker,  we move away from postgres to h2 to demonstrate JDBC access.

**Comment by kenfinnigan** [comment]
Closing as it now uses h2 for local usage
